### ISSUE TITLE
METAR-RaspPi Not Parsing WX Remarks, Cloud Graph Issue

### ISSUE THREAD

**Issue by spenadel** [flyinactor91/METAR-RasPi#1]
Hi - 

Love this project.  I've found that the WX/RMK page does not parse the METAR remarks.  For example, HZ is parsed as H,Z.  VCTS instead of being parsed as Thunderstorms in Vicinity, it's being displayed as V,C,T,S.

The other thing that I'm seeing is the degrees symbol in STD (for deviation from standard temp) is being covered by the vertical cloud coverage bar when the STD exceeds one digit.  It's currently showing +11 and the symbol is covered.

**Comment by devdupont** [comment]
Ok. I’ll check that out. I need to get it running again for multiple screen sizes too. Wonder if config files for element locations would be the best way to go.

**Comment by spenadel** [comment]
Thank you for responding.  Love this application.  May build one for my flying club too using a 7" TFT screen.

Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by devdupont** [comment]
Just realized I never closed this. Graph should be fixed, and the JSON layout config was implemented.
